---
title: "JohnSnow"
author: "Joshua"
date: "11 septembre 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("ggplot2")
#install.packages("ggmap")
#install.packages("sf")
#install.packages("rgdal")
#install.packages("leaflet")
#install.packages("readxl")
#install.packages("raster")
library(leaflet)
library(ggplot2)
library(ggmap)
require(rgdal) 
library(readxl)
library(raster)
```

## R Markdown


##Getting a Map object.
```{r}
#test <- ggmap::get_stamenmap(bbox = c(left = 6.15, bottom = 49.10, right = 6.20, top = 49.15), zoom = 14, maptype="watercolor")
test <- ggmap::get_stamenmap(bbox = c(left = 6.15, bottom = 49.10, right = 6.20, top = 49.15), zoom = 14, maptype="watercolor")
ggmap::ggmap(test)
```


##Getting the data from the shapefiles
```{r}
unzip('SnowGIS_SHP.zip')
deaths <- rgdal::readOGR(dsn = "SnowGIS_SHP/", layer = "Cholera_Deaths")
deaths_f <- fortify(deaths@data)
deaths_f$Count <- as.numeric(as.character(deaths$Count)) #Converts the Count column to double
#deaths_f$Id <- as.numeric(as.character(deaths$Id)) #Converts the Id column to double
deaths_f$Id <- NULL #Deletes Id column


pumps <- rgdal::readOGR(dsn = "SnowGIS_SHP/", layer = "Pumps")
pumps_f <- fortify(pumps@data)
#deaths_f$Count <- as.numeric(as.character(deaths$Count)) #Converts the Count column to double
#deaths_f$Id <- as.numeric(as.character(deaths$Id)) #Converts the Id column to double
#deaths_f$Id <- NULL #Deletes Id column

data_f <- as.data.frame(deaths@coords) #Creates an array with coordinates and counts of deaths
data_f$Count <- deaths$Count

#lol <- pairs(data_f$coords.x1, data_f$coords.x2)
#data_f$Coords <- c(data_f$coords.x1, data_f$coords.x2)
data_test <- as.data.frame(deaths@coords)
pumps_test <- as.data.frame(pumps@coords)


rel <- raster("SnowGIS_SHP/OSMap.tif")
#plot(rel)
rel_spdf <- as(rel, "SpatialPixelsDataFrame")
rel <- as.data.frame(rel_spdf)


ggplot() +
  #Comment next line to only plot the points
  geom_raster(data = rel, aes_string(x = "x", y = "y", alpha = "OSMap")) +
  scale_alpha(name = "", range = c(0.6, 0), guide = F) +
  #Comment both following lines and uncomment first line of this block to only plot the map
  #geom_count(data = data_f, aes(x = "coords.x1", y = "coords.x2"), colour = "black", size = 1) +
  geom_point(data = data_test, aes(x = coords.x1, y = coords.x2), colour = "black", size = 1) +
  geom_point(data = pumps_test, aes(x = coords.x1, y = coords.x2), colour = "red", size = 1)




```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
